name: Composite vs Reusable
on:
  push:
    paths:
    - .github/workflows/call-composite-action-reusable-workflow.yml
    - .github/my-composite-action/*.*
    
  workflow_dispatch:
    
jobs:
  composite-action:
    name: Calling composite action
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello from example job"
    - uses: actions/checkout@v3
    - uses: ./.github/my-composite-action
    
  reusable-workflow:
    name: Calling reusable workflow
    uses: ./.github/workflows/reusable-workflow.yml
    with:      
      config-path: .github/workflows
    secrets:
      token: ${{ github.token }}
