on:
  workflow_dispatch:
  
  push:
    paths: 
      - .github/workflows/demo-day1.yaml
      
permissions:
  contents: read

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{runner.tool_cache}}
      
