# This is a basic workflow to help you get started with Actions

name: CI demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]    
    paths:
      - .github/workflows/demo.yml
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This is the first job
  init: 
    name: Friendly name for the UI
    runs-on: ubuntu-latest
    steps: 
      - run: echo Hello init
    
  # This is the second job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: init

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:          
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x

      - run: node --version

  # This is the third job
  parallel: 
    name: Third job
    runs-on: ubuntu-latest
    steps: 
      - run: echo Hello init
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:          
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.x
