name : run Trivy scan
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/docker-scan.yml
jobs:
  docker-scan:
    runs-on: ubuntu-latest
    steps: # docker://ghcr.io/calibreapp/image-actions/image-actions:main
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/calibreapp/image-actions/image-actions:main"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          format: "table"
          #template: "@/contrib/sarif.tpl"
          #output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
