name: harden runner
on:
  workflow_dispatch:
  
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
      
      - run: terraform version
