name: Issue management

on:
  issues:
    types: [opened, assigned, closed]

# map fields with customized labels
env:
  todo: Todo
  assigned: Assigned
  done: Done

  project-owner: 'rajbos'
  project-number: 5
  ISSUE_URL: "${{ github.event.issue.html_url }}"

permissions:
  issues: write
  repository-projects: write

jobs:
  issue-created:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository == 'rajbos/demo-actions'    
    steps:
      - name: Instal gh projects extension
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh extension install github/gh-projects
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - name: add-issue-to-project
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           echo "${{ toJSON(github.event.issue) }}"
           gh projects item-add $project-number --user "@me" --url "$ISSUE_URL"

      - name: Moved issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@939000fb1900c9fc4f7b5058a09d9f833ebc6859
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          user: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status

  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned' && github.repository == 'rajbos/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.assigned }}
        uses: leonsteinhaeuser/project-beta-automations@939000fb1900c9fc4f7b5058a09d9f833ebc6859
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          user: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.assigned }} # Target status

  issue-closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed' && github.repository == 'rajbos/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@939000fb1900c9fc4f7b5058a09d9f833ebc6859
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          user: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
