name: model-training-evaluate
on: 
  push:
     paths: .github/workflows/machine-learning.yml
  workflow_dispatch:
  
jobs:
   run:
     runs-on: [ubuntu-latest]
     container: docker://dvcorg/cml-py3:latest
     steps:
       - uses: actions/checkout@v3
         with:
           repository: mlops-guide/dvc-gitactions
       
       - name: 'Train and Evaluate model'
         shell: bash
         env:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
           # Install requirements
           pip install -r requirements.txt

           dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data/data.xml
           dvc add data/data.xml
           # Pull data & run-cache from IBM COS and reproduce pipeline          
                      
           dvc pull --run-cache --local
           dvc repro

           # Report metrics
           echo "## Metrics" >> report.md
           git fetch --prune
           dvc metrics diff master --show-md >> report.md

           # Publish ROC Curve and 
           echo -e "## Plots\n### ROC Curve" >> report.md
           cml-publish ./results/roc_curve.png --md >> report.md
           echo -e "\n### Precision and Recall Curve" >> report.md
           cml-publish ./results/precision_recall_curve.png --md >> report.md
           cml-send-comment report.md
