name: Demo the matrix

on:
  push:
    paths: 
      - .github/workflows/matrix.yml
  workflow_dispatch:
      
jobs:
  job-1:
    runs-on: ${{ matrix.label }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        label: [ubuntu-latest, ubuntu-22.04-arm64, ubuntu-24.04-arm64]
    steps:
     - run: |
         echo "Hello world"
         echo "Node-version: ${{ matrix.node-version }} for os ${{ matrix.label }}"
