name: Run local Docker action
on: 
  push:
  workflow_dispatch:
    
jobs:
  call-local-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/my-docker-action

