name: Notify on new issue

on:
  issues:
    types: [opened]
    
jobs:
  tag-a-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
      - uses: devops-actions/issue-comment-tag@v0.1.4
        name: Tag a user or team in an issue comment
        with: 
          issue: ${{ github.event.issue.number }}
          team: 'rajbos'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo "Hi Rob, there is a new issue in ${{ github.repository }}" > $GITHUB_STEP_SUMMARY
   
   
   
   
   
  slack-notify:
    runs-on: ubuntu-latest
    needs: tag-a-user
    steps:    
      - name: 'Post summary'
        uses: crederauk/slack-workflow-summary@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          success-emoji: ':heavy-check-mark:'
          skipped-emoji: ':heavy-minus-sign:'
          failed-emoji: ':heavy-cross-mark:'
