name: Notify on new issue

on:
  issues:
    types: [opened]
    
jobs:
  tag-a-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
      - uses: devops-actions/issue-comment-tag@v0.1.8
        name: Tag a user or team in an issue comment
        with: 
          issue: ${{ github.event.issue.number }}
          team: 'rajbos'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
   
   
   
   
   
   
   
   
  slack-notify:
    runs-on: ubuntu-latest
    needs: tag-a-user
    steps:    
      - uses: rajbos-actions/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
        with: 
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
  check-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
      - env:
          data:  ${{ toJSON(github.event.issue) }}
        run: |
          echo $data
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        name: Close the issue if the name contains 💩
        with:
           script: |              
            const script = require('.github/workflows/scripts/new-issue-created.js')
            const title = '${{ github.event.issue.title }}'
            console.log(script({github, context, title}))
            
        
