name: Process Ids
on: 
  push:
    paths:
    - .github/workflows/process-ids.yml
    
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
    - run: echo $$
