name: Run job in container
on:
  push:
    paths:
      .github/workflows/run-in-container.yml
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World"
      - run: whoami
