name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted-check.yml
      
env:
  organization: 'devops-actions'
jobs:
  self-hosted-number:
    runs-on: ubuntu-latest
    steps:
       - uses: devops-actions/load-runner-info@v1.0.6
         id: load-runner-info-org
         with: 
           accessToken: ${{ secrets.PAT }}
           organization: ${{ env.organization }}
           
