name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted2.yml
permissions:
  contents: read

jobs:
  self-hosted-number2:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir npm-cli2
           cd npm-cli2
           git clone https://github.com/npm/cli.git
           
