name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted2.yml
jobs:
  self-hosted-number2:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v3
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir npm-cli2
           cd npm-cli2
           git clone https://github.com/npm/cli.git
           
