name: self-hosted check runners
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted-check.yml
      
env:
  organization: 'devops-actions'
jobs:
  self-hosted-number:
    runs-on: ubuntu-latest
    steps:
     - uses: devops-actions/load-runner-info@v1.0.9
       id: load-runner-info-org
       with: 
         accessToken: ${{ secrets.PAT }}
         organization: ${{ env.organization }}
         
     - uses: actions/github-script@v5
       name: debugging
       with: 
          script: |
            const info = JSON.parse(`${{ steps.load-runner-info-org.outputs.runners }}`)   
            console.log(info)
            
            console.log('----------------')
            console.log(info.length)

     - uses: actions/github-script@v5
       name: Test runner info
       with: 
          script: |
            const info = JSON.parse(`${{ steps.load-runner-info-org.outputs.runners }}`)
            if (info.length == 0) {
              core.error('No runners found')            
              return
            }
            
            console.log(`Found [${info.length}] runner(s)`)
            for (let num = 0; num < info.length; num++) {
              const runner = info[num]
              console.log(`- name: [${runner.name}]`)
            }

            console.log(``)
            const grouped = JSON.parse(`${{ steps.load-runner-info-org.outputs.grouped }}`)

            // example of a test you can do on the amount of runners online with this label
            const selfHosted = grouped.find(group => group.name === 'self-hosted')
            if (selfHosted.status == 1) {
              core.info(`Found the expected amount of runners with label "self-hosted"`)
              // write the info the the summary
              core.summary
                .addRaw(`:green_circle: Found the expected amount of runners with label "self-hosted"`)
                .write()
              return
            }
            else {
              core.error(`Found an unexpected amount of runners with label "self-hosted": ${selfHosted.status}`)
              // write the info the the summary
              core.summary
                .addRaw(`:red_circle: Found an unexpected amount of runners with label "self-hosted": ${selfHosted.status}`)
                .write()
              return
            }

            // example of a test you can do on the amount of runners online with this label
            if (selfHosted.status < selfHosted.counter) {
              core.error(`There are [${selfHosted.counter - selfHosted.status}] runners offline`)
              // write the info the the summary
              core.summary
                .addRaw(`:red_circle: There are [${selfHosted.counter - selfHosted.status}] runners offline`)
                .write()
              return
            }
