name: self-hosted
on:
  workflow_dispatch:
  push:
    paths: 
      - .github/workflows/self-hosted.yml
jobs:
  self-hosted-number1:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v3
       - run: echo "Hello world"
       
       - name: Checkout Git repo manually
         run: |
           mkdir npm-cli
           cd npm-cli
           git clone https://github.com/npm/cli.git
           
       - uses: actions/setup-dotnet@v3
         with:
           dotnet-version: '5.x'
       - run: dotnet --version
       

       - uses: actions/setup-node@v3
         with:
           node-version: '14'
       - run: npm version
