on:
  workflow_dispatch:
    inputs:
      abc:
        description: test
        type: string

  #push:
        
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.abc }}
