name: Vulnerable example workflow
on:
  pull_request:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      # run the vulnerable script:
      - name: PR Title
        continue-on-error: true
        run: | 
          echo "Title: ${{ github.event.pull_request.title }}"

      - name: ref
        continue-on-error: true
        run: |
          echo "GitHub Ref: ${{ github.ref }}"

      - name: head_ref
        continue-on-error: true
        run: |
          echo "GitHub head_ref: ${{ github.head_ref }}"

      - name: ref_name
        continue-on-error: true
        run: |
          echo "GitHub ref_name: ${{ github.ref_name }}"
          
      - name: Test
        continue-on-error: true
        run: |
           GITHUB_REF_NAME=${{ github.ref_name }}           

      # test in a composite action file:
      - uses: actions/checkout@v4
      # run the vulnerable action:
      - uses: ./.github/vulnerable-action
      
