name:
  workflow_debug
on:
  push:
    paths:
    - .github/workflows/workflow_debug.yml
    
permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "ACTIONS_STEP_DEBUG: [${{ env.ACTIONS_STEP_DEBUG }}]"
        echo "ACTIONS_RUNNER_DEBUG: [${{ env.ACTIONS_RUNNER_DEBUG }}]"
        echo "STEP_DEBUG: [${{ env.STEP_DEBUG }}]"
        echo "RUNNER_DEBUG: [${{ env.RUNNER_DEBUG }}]"
        
        echo "RUNNER_DEBUG: [${{ runner.debug }}]"
        
    - name: Log github context
      env:
        context: ${{ toJSON(github) }}
      run: |
        echo "$context"
        
    - name: Log job context
      env:
        context: ${{ toJSON(job) }}
      run: |
        echo "$context"
    
    - name: Log env context
      env:
        context: ${{ toJSON(env) }}
      run: |
        echo "$context"
